### PR TITLE
New Logo file removed

### PR DESCRIPTION
**Pull request by ska-ibees**
New Logo file removed

### CODE REVIEW

**Comment by ska-ibees** [comment]
@JuanDCG Plz check this one.

**Review by JuanDCG — COMMENTED** [review]
here:

assets/images/Terradoo-new-logo.png

**Comment by ska-ibees** [comment]
OMG, I have done it multiple times but this git thing is...

**Review by JuanDCG — APPROVED** [review]

**Comment by JuanDCG** [comment]
Ok, we are starting and need more practice with Git and Github workflow.

**Pull request closed without merging**
